//! `avp intent {claim|overlap|merge-order|verify}` — git-aware
//! coordination over `.avp-intent.toml`.
//!
//! Discovery shells to `git`: `git for-each-ref refs/heads/*` to
//! enumerate branches, `git show <ref>:.avp-intent.toml` to read each
//! branch's claim without checking it out.
//!
//! Schema + lifecycle live in `cross-repo/multi-instance.md`. This
//! module is the CLI surface; the parser + types live in
//! `avp_core::intent`.

#![allow(clippy::disallowed_macros)]

use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    fmt::Write as _,
    fs,
    path::Path,
    process::{Command, ExitCode},
};

use anyhow::{Context as _, Result, anyhow};
use avp_core::{AgentId, IntentFile};
use time::{OffsetDateTime, format_description::well_known::Rfc3339};
use tracing::{debug, info, instrument, warn};

// ─────────────────────────────────────────────────────────────────────────
// claim
// ─────────────────────────────────────────────────────────────────────────

/// Inputs for `avp intent claim`.
#[derive(Debug)]
pub(crate) struct ClaimRequest {
    pub repo: std::path::PathBuf,
    pub agent_id: String,
    pub branch: String,
    pub goal: String,
    pub success_test: String,
    pub declared_files: Vec<String>,
    pub allows_overlap_with: Vec<String>,
    pub expected_pr: Option<String>,
    pub expires_after: Option<String>,
    pub force: bool,
}

/// Top-level entry for `claim`. Validates against active intents on
/// other branches, then writes `.avp-intent.toml` at repo root.
#[instrument(level = "debug", skip_all, fields(repo = %req.repo.display(), agent = %req.agent_id))]
pub(crate) fn claim(req: &ClaimRequest) -> Result<ExitCode> {
    let intent_path = req.repo.join(".avp-intent.toml");
    if intent_path.exists() && !req.force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            intent_path.display()
        ));
    }

    // Render TOML deterministically.
    let body = render_claim_toml(req)?;
    // Validate by round-tripping through the parser (catches typos /
    // bad combinations before we write to disk).
    let candidate =
        IntentFile::from_toml(&body).context("rendered claim failed validation; this is a bug")?;

    // Pre-claim conflict check against every other active intent.
    let actives = scan_active_intents(&req.repo).unwrap_or_else(|err| {
        warn!(?err, "intent scan failed; proceeding without overlap check");
        Vec::new()
    });
    let mut conflicts = Vec::new();
    for other in &actives {
        if other.agent_id == candidate.agent_id {
            continue; // re-claiming same intent on same branch is fine
        }
        let shared = candidate.pattern_overlap(other);
        if shared.is_empty() {
            continue;
        }
        if candidate.overlap_allowed_with(other) {
            info!(other = %other.agent_id, files = ?shared, "overlap explicitly allowed");
            continue;
        }
        conflicts.push((other.agent_id.clone(), shared));
    }

    if !conflicts.is_empty() && !req.force {
        for (other, files) in &conflicts {
            eprintln!(
                "::error::intent overlap with {} on files: {}",
                other,
                files.join(", ")
            );
        }
        return Err(anyhow!(
            "{} overlap conflict(s); resolve with allows_overlap_with or pick disjoint files",
            conflicts.len()
        ));
    }

    fs::write(&intent_path, &body).with_context(|| format!("write {}", intent_path.display()))?;
    info!(path = %intent_path.display(), "intent claimed");
    println!(
        "claimed: {} ({} declared file(s))",
        candidate.agent_id,
        candidate.declared_files.len()
    );
    Ok(ExitCode::SUCCESS)
}

/// Render the canonical TOML body for an intent. Field order is fixed
/// so re-claims diff cleanly.
fn render_claim_toml(req: &ClaimRequest) -> Result<String> {
    // Guard: validate the agent id shape now so we fail fast with a
    // shaped error before writing a file that the parser would reject.
    let _ = AgentId::new(req.agent_id.clone()).context("agent_id")?;

    let opened = OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .context("format opened_at")?;

    let mut s = String::new();
    let _ = writeln!(s, "# .avp-intent.toml — generated by `avp intent claim`.");
    let _ = writeln!(
        s,
        "# Schema: PlausiDen-AVP-Doctrine/cross-repo/multi-instance.md"
    );
    let _ = writeln!(s, "agent_id     = {}", quoted(&req.agent_id));
    let _ = writeln!(s, "branch       = {}", quoted(&req.branch));
    let _ = writeln!(s, "goal         = {}", quoted(&req.goal));
    let _ = writeln!(s, "success_test = {}", quoted(&req.success_test));
    let _ = writeln!(s, "opened_at    = {}", quoted(&opened));
    let _ = writeln!(s, "declared_files = [");
    for f in &req.declared_files {
        let _ = writeln!(s, "    {},", quoted(f));
    }
    let _ = writeln!(s, "]");
    if !req.allows_overlap_with.is_empty() {
        let _ = writeln!(s, "allows_overlap_with = [");
        for a in &req.allows_overlap_with {
            let _ = writeln!(s, "    {},", quoted(a));
        }
        let _ = writeln!(s, "]");
    }
    if let Some(pr) = &req.expected_pr {
        let _ = writeln!(s, "expected_pr   = {}", quoted(pr));
    }
    if let Some(exp) = &req.expires_after {
        let _ = writeln!(s, "expires_after = {}", quoted(exp));
    }
    Ok(s)
}

/// TOML basic-string with conservative escaping (covers "" and \).
fn quoted(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

// ─────────────────────────────────────────────────────────────────────────
// overlap
// ─────────────────────────────────────────────────────────────────────────

/// Report file-touch overlap across every active intent in the repo.
#[instrument(level = "debug", skip_all)]
pub(crate) fn overlap(repo: &Path) -> Result<ExitCode> {
    let intents = scan_active_intents(repo)?;
    if intents.len() < 2 {
        println!("overlap: {} intent(s); nothing to compare", intents.len());
        return Ok(ExitCode::SUCCESS);
    }

    let mut collisions: Vec<(String, String, Vec<String>)> = Vec::new();
    for i in 0..intents.len() {
        for j in (i + 1)..intents.len() {
            let a = &intents[i];
            let b = &intents[j];
            let shared = a.pattern_overlap(b);
            if shared.is_empty() {
                continue;
            }
            if a.overlap_allowed_with(b) {
                continue;
            }
            collisions.push((a.agent_id.to_string(), b.agent_id.to_string(), shared));
        }
    }

    if collisions.is_empty() {
        println!("overlap: clean ({} active intents)", intents.len());
        return Ok(ExitCode::SUCCESS);
    }
    for (a, b, shared) in &collisions {
        println!("overlap: {a} ↔ {b}");
        for f in shared {
            println!("  - {f}");
        }
        println!("  resolution: add `allows_overlap_with = [\"{a}\"]` to one side, or coordinate.");
    }
    Err(anyhow!(
        "{} overlap collision(s) across {} intents",
        collisions.len(),
        intents.len()
    ))
}

// ─────────────────────────────────────────────────────────────────────────
// merge-order
// ─────────────────────────────────────────────────────────────────────────

/// Topologically sort active intents into a merge order.
#[instrument(level = "debug", skip_all)]
pub(crate) fn merge_order(repo: &Path) -> Result<ExitCode> {
    let intents = scan_active_intents(repo)?;
    if intents.is_empty() {
        println!("merge-order: 0 active intents");
        return Ok(ExitCode::SUCCESS);
    }

    // Build edges: (earlier opened_at) → (later opened_at) when they
    // share files. The earlier intent merges first; the later one
    // rebases onto main after.
    let mut edges: HashMap<String, BTreeSet<String>> = HashMap::new();
    for a in &intents {
        edges.entry(a.agent_id.to_string()).or_default();
    }
    for i in 0..intents.len() {
        for j in (i + 1)..intents.len() {
            let a = &intents[i];
            let b = &intents[j];
            if a.pattern_overlap(b).is_empty() {
                continue;
            }
            let (first, second) = if a.opened_at <= b.opened_at {
                (a, b)
            } else {
                (b, a)
            };
            edges
                .entry(first.agent_id.to_string())
                .or_default()
                .insert(second.agent_id.to_string());
        }
    }

    // Kahn's algorithm: repeatedly pick a node with no incoming edges.
    let mut incoming: HashMap<String, u32> = intents
        .iter()
        .map(|i| (i.agent_id.to_string(), 0))
        .collect();
    for tos in edges.values() {
        for to in tos {
            *incoming.entry(to.clone()).or_default() += 1;
        }
    }
    let mut order: Vec<String> = Vec::with_capacity(intents.len());
    loop {
        // Stable: pick the lexicographically-smallest agent id with 0 incoming.
        let next = incoming
            .iter()
            .filter(|(_, n)| **n == 0)
            .map(|(k, _)| k.clone())
            .min();
        let Some(next) = next else { break };
        incoming.remove(&next);
        if let Some(tos) = edges.get(&next) {
            for to in tos {
                if let Some(n) = incoming.get_mut(to) {
                    *n = n.saturating_sub(1);
                }
            }
        }
        order.push(next);
    }

    if !incoming.is_empty() {
        return Err(anyhow!(
            "merge-order: cycle in intent DAG ({} nodes unresolved)",
            incoming.len()
        ));
    }

    let by_id: BTreeMap<String, &IntentFile> = intents
        .iter()
        .map(|i| (i.agent_id.to_string(), i))
        .collect();
    for (i, id) in order.iter().enumerate() {
        let intent = by_id.get(id).expect("present by construction");
        let blocks: Vec<String> = edges
            .get(id)
            .map(|s| s.iter().cloned().collect())
            .unwrap_or_default();
        println!("{}. {}  ({})", i + 1, id, intent.branch);
        println!("   declared: {}", intent.declared_files.join(", "));
        if !blocks.is_empty() {
            println!("   blocks:   [{}]", blocks.join(", "));
        }
    }
    Ok(ExitCode::SUCCESS)
}

// ─────────────────────────────────────────────────────────────────────────
// verify
// ─────────────────────────────────────────────────────────────────────────

/// CI gate: load the current branch's intent and check that the diff
/// against `--base` ref doesn't exceed `declared_files`.
#[instrument(level = "debug", skip_all)]
pub(crate) fn verify(repo: &Path, base: &str) -> Result<ExitCode> {
    let intent_path = repo.join(".avp-intent.toml");
    if !intent_path.is_file() {
        return Err(anyhow!(
            "{} missing; every conductor-managed branch must have an intent",
            intent_path.display()
        ));
    }
    let intent = IntentFile::load(&intent_path)?;

    let now = OffsetDateTime::now_utc().date();
    if intent.is_expired(now) {
        return Err(anyhow!(
            "intent expired (expires_after past). archive or refresh the claim."
        ));
    }

    let changed = changed_files(repo, base)?;
    let mut over: Vec<String> = Vec::new();
    for f in &changed {
        if !intent.matches_path(f) && f != ".avp-intent.toml" {
            over.push(f.clone());
        }
    }
    if !over.is_empty() {
        for f in &over {
            eprintln!(
                "::error::file `{f}` is outside declared_files of intent {}",
                intent.agent_id
            );
        }
        return Err(anyhow!(
            "{} file(s) modified outside declared scope",
            over.len()
        ));
    }
    println!(
        "intent verify: clean ({} declared, {} changed)",
        intent.declared_files.len(),
        changed.len(),
    );
    Ok(ExitCode::SUCCESS)
}

// ─────────────────────────────────────────────────────────────────────────
// git plumbing
// ─────────────────────────────────────────────────────────────────────────

/// Enumerate every local branch and read its `.avp-intent.toml` if
/// present. Branches that fail to parse are warned and skipped — one
/// broken intent shouldn't block the rest.
#[instrument(level = "debug", skip_all)]
fn scan_active_intents(repo: &Path) -> Result<Vec<IntentFile>> {
    let branches = list_branches(repo)?;
    let mut intents = Vec::new();
    for branch in branches {
        match read_intent_at_ref(repo, &branch) {
            Ok(Some(intent)) => intents.push(intent),
            Ok(None) => debug!(branch = %branch, "no intent on branch"),
            Err(err) => warn!(branch = %branch, ?err, "intent read failed"),
        }
    }
    Ok(intents)
}

fn list_branches(repo: &Path) -> Result<Vec<String>> {
    let out = run_git(
        repo,
        &["for-each-ref", "--format=%(refname:short)", "refs/heads/"],
    )?;
    Ok(out
        .lines()
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
        .collect())
}

fn read_intent_at_ref(repo: &Path, branch: &str) -> Result<Option<IntentFile>> {
    let spec = format!("{branch}:.avp-intent.toml");
    let Some(out) = run_git_quiet(repo, &["show", &spec])? else {
        return Ok(None);
    };
    let intent = IntentFile::from_toml(&out)?;
    Ok(Some(intent))
}

fn changed_files(repo: &Path, base: &str) -> Result<Vec<String>> {
    let out = run_git(repo, &["diff", "--name-only", base, "--"])?;
    Ok(out
        .lines()
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
        .collect())
}

fn run_git(repo: &Path, args: &[&str]) -> Result<String> {
    let output = Command::new("git")
        .current_dir(repo)
        .args(args)
        .output()
        .with_context(|| format!("spawn git {args:?}"))?;
    if !output.status.success() {
        return Err(anyhow!(
            "git {:?} exited {}: {}",
            args,
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    String::from_utf8(output.stdout).map_err(|e| anyhow!("git stdout not utf-8: {e}"))
}

/// Like `run_git` but treats nonzero exit (e.g., "path doesn't exist on
/// this ref") as `Ok(None)` rather than an error. Used by intent-show
/// where an absent file is the common case.
fn run_git_quiet(repo: &Path, args: &[&str]) -> Result<Option<String>> {
    let output = Command::new("git")
        .current_dir(repo)
        .args(args)
        .output()
        .with_context(|| format!("spawn git {args:?}"))?;
    if !output.status.success() {
        return Ok(None);
    }
    let s = String::from_utf8(output.stdout).map_err(|e| anyhow!("git stdout not utf-8: {e}"))?;
    if s.trim().is_empty() {
        return Ok(None);
    }
    Ok(Some(s))
}

// ─────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quoted_escapes() {
        assert_eq!(quoted("plain"), "\"plain\"");
        assert_eq!(quoted(r#"with "quote""#), r#""with \"quote\"""#);
        assert_eq!(quoted(r"with\backslash"), r#""with\\backslash""#);
    }

    #[test]
    fn render_claim_round_trips() {
        let req = ClaimRequest {
            repo: std::path::PathBuf::from("/tmp/x"),
            agent_id: "claude-2026-05-01-T01".into(),
            branch: "claude/test".into(),
            goal: "g".into(),
            success_test: "cargo test".into(),
            declared_files: vec!["a.toml".into()],
            allows_overlap_with: vec![],
            expected_pr: None,
            expires_after: None,
            force: false,
        };
        let toml = render_claim_toml(&req).unwrap();
        let parsed = IntentFile::from_toml(&toml).unwrap();
        assert_eq!(parsed.agent_id.as_str(), "claude-2026-05-01-T01");
        assert_eq!(parsed.declared_files, vec!["a.toml".to_owned()]);
    }

    #[test]
    fn render_claim_with_overlap_allowance() {
        let req = ClaimRequest {
            repo: std::path::PathBuf::from("/tmp/x"),
            agent_id: "a".into(),
            branch: "b".into(),
            goal: "g".into(),
            success_test: "t".into(),
            declared_files: vec![],
            allows_overlap_with: vec!["other".into()],
            expected_pr: Some("org/repo#1".into()),
            expires_after: Some("2026-12-31".into()),
            force: false,
        };
        let toml = render_claim_toml(&req).unwrap();
        assert!(toml.contains("expected_pr"));
        assert!(toml.contains("expires_after"));
        let parsed = IntentFile::from_toml(&toml).unwrap();
        assert_eq!(parsed.allows_overlap_with.len(), 1);
        assert_eq!(parsed.expected_pr.as_deref(), Some("org/repo#1"));
    }

    #[test]
    fn render_claim_invalid_agent_fails_fast() {
        let req = ClaimRequest {
            repo: std::path::PathBuf::from("/tmp/x"),
            agent_id: "has space".into(),
            branch: "b".into(),
            goal: "g".into(),
            success_test: "t".into(),
            declared_files: vec![],
            allows_overlap_with: vec![],
            expected_pr: None,
            expires_after: None,
            force: false,
        };
        assert!(render_claim_toml(&req).is_err());
    }
}
